### PR TITLE
Stroked the border

### PR DESCRIPTION
**Pull request by gSpera**
Hi, I am using regularly pages generated by this tool but the results are not great as I was expetting. I noticed that increasing the stroke of the outer border helps the app to scan better.
This pull is not complete, the PDF are not generated but I wanted to start a discussion about this issue.
Thanks

### CODE REVIEW

**Comment by FranciscodeMaussion** [comment]
LGTM. Im not actively using this so someone else may check.

**Comment by gSpera** [comment]
Also a lot of space seems (to me) to be wasted, the border could be more near the border of the paper

**Comment by FranciscodeMaussion** [comment]
yes, that was not a decistion really. I use the one given by the rocketbook company.

**Comment by gSpera** [comment]
Ok, so what are we gonna do??
I would like the template to be fullpage, this way is possible to resize everything using only the printer tool, removing waste of space.
I didn't change anything so prabably QR Codes would be generated wrongly.
This would be a breaking change, maybe we should enable this by a flag.
Also I don't know how to build the PDFs, would be great to set up a Makefile or a bash script that uses the inkscape cli interface

Tell me what you think

**Comment by FranciscodeMaussion** [comment]
Have you tested the other PR? That one help you make a custom template. Maybe that is the solution. The pdf I edited directly from inkscape.

**Comment by gSpera** [comment]
Actually for me testing is a little bit difficult, I tested briefly the Fullpage SVG file and seems to work well, I didn't generated the PDFs because i don't know how to do that.

**Comment by FranciscodeMaussion** [comment]
Hi!!! I have changed a little bit the idea of the project, you can now share your template files. Ex: you want to have a template with a big circle in the middle, you can create a template for that!!! 
The page size are standard and you can get them from reportlab. The qr position is a difficult one yet...
I will reject this MR but feel free to share your template as a new template file.

**Pull request closed without merging**
